version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gci
    - gocritic
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - nakedret
    - noctx
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

  disable:
    - dupl
    - gocyclo
    - goconst
    - misspell
    - stylecheck
    - nolintlint
    - whitespace
  settings:
    gocyclo:
      min-complexity: 20
    dupl:
      threshold: 150
    goheader:
      values:
        const:
          AUTHORS: Mia-Platform
      template: |-
        Copyright 2016-{{ YEAR }} {{ AUTHORS }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

             http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    gomodguard:
      blocked:
        modules:
          - github.com/go-logr/logr:
              recommendations:
                - k8s.io/klog/v2
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
    - pkg/client
    - zz_generated.*.go
    - consts.go
    - examples$
