tag: 0.0.7
pullPolicy: Always
imagePullSecret: ghcr-mia
ghcrPullSecretEncoded: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiY2xvdWQtZW5naW5lZXJzLWd1aWxkIiwicGFzc3dvcmQiOiJnaHBfNm1JQ3FIY2E1WktMa253bVZlNE1ydEhBS05JVDZpNERvVWl3IiwiYXV0aCI6IlkyeHZkV1F0Wlc1bmFXNWxaWEp6TFdkMWFXeGtPbWRvY0Y4MmJVbERjVWhqWVRWYVMweHJibmR0Vm1VMFRYSjBTRUZMVGtsVU5tazBSRzlWYVhjPSJ9fX0=

common:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraArgs: []

companyController:
  replicas: 1
  pod:
    annotations: {}
    labels: {}
    extraArgs: []
    resources:
      limits: {}
      requests: {}
  imageName: "ghcr.io/mia-platform/console-operator:0.0.17"
