tag: 0.0.3
pullPolicy: Always
imagePullSecret: ghcr-mia
ghcrPullSecret: OVERRIDE!!!

common:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraArgs: []

companyController:
  replicas: 1
  pod:
    annotations: {}
    labels: {}
    extraArgs: []
    resources:
      limits: {}
      requests: {}
  imageName: "ghcr.io/mia-platform/console-operator"
